---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        exclude: build/
      - id: destroyed-symlinks
      - id: detect-private-key
        exclude: .github/linters
      - id: check-ast
      - id: check-case-conflict
      - id: debug-statements
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.2.0
    hooks:
      - id: detect-secrets
        exclude: build/|.travis.yml|.github/linters
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.49.0
    hooks:
      - id: golangci-lint
  # - repo: https://github.com/tekwizely/pre-commit-golang
  #   rev: v1.0.0-beta.5
  #   hooks:
  #       - id: go-mod-tidy
  #       - id: go-test-mod
  #       - id: go-revive
  #       - id: go-sec-mod
  #       - id: go-lint
  #       # -   id: go-critic
  #       # -   id: golangci-lint
