---
###########################
###########################
## Markdown Linter rules ##
###########################
###########################

###############
# Rules by id #
###############
MD004: false                  # Unordered list style
MD014: false
MD024: false
MD007:
  indent: 2                   # Unordered list indentation
MD013:
  line_length: 400            # Line length 80 is far to short
MD026:
  punctuation: ".,;:!。，；:"  # List of not allowed
MD029: false                  # Ordered list item prefix
MD033: false                  # Allow inline HTML
MD036: false                  # Emphasis used instead of a heading

#################
# Rules by tags #
#################
blank_lines: false  # Error on blank lines
